name: Changesets

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

  push:
    branches: [main]

jobs:
  check-for-changeset:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Verify changeset existence
        run: npx changeset status --since origin/main

  release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Load SSH signing key
        run: |
          echo "${{ secrets.SSH_SIGNING_PK }}" > /tmp/.git_signing_key
          chmod 600 /tmp/.git_signing_key
        shell: bash

      - name: Set git user
        shell: bash
        run: |
          git config user.name "isburnt"
          git config user.email "197779235+isburnt@users.noreply.github.com"
          git config commit.gpgsign true
          git config gpg.format ssh
          git config user.signingkey /tmp/.git_signing_key

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          publish: false
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
