name: GitHub Pages

on:
  workflow_run:
    workflows: ["Test"]
    types: [completed]
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build
        run: |
          npm i
          npm run build
        env:
          NEXT_PUBLIC_IS_DEPLOYMENT: "true"
          NEXT_PUBLIC_IS_PRO_MODE: "false"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
